### ISSUE TITLE
WARNING MaxDb   GetVendor: '-1' not found. IF PTPMonkey Plugin is loaded

### ISSUE THREAD

**Issue by Twister10000** [martim01/pam#68]
Hello 

when I add the PTP plugin and restart PAM I always get the following error message:
WARNING MaxDb GetVendor: '-1' not found.

**Comment by martim01** [comment]
When the PTP plugin sees a message from a clock or "client" it attempts to lookup the MAC address that is in the message to give some more detail about the sender. The above WARNING is a misspelling it should be "MAC DB GetVendor not found". It should also have been a TRACE message rather than a warning so I've removed it and corrected the spelling mistakes elsewhere in that file
